issuer: https://token.actions.githubusercontent.com
subject: repo:jakebailey/hereby:ref:refs/heads/main
claim_pattern:
  workflow_ref: jakebailey/hereby/\.github/workflows/changesets\.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
