issuer: https://token.actions.githubusercontent.com
subject: repo:jakebailey/hereby:environment:npm
claim_pattern:
  workflow_ref: jakebailey/hereby/\.github/workflows/release\.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
