name: Changesets

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest

    permissions:
      contents: write
      checks: read
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          filter: blob:none
          # We clone using a deploy key so that this workflow can
          # push tags and trigger the release workflow, which GHA
          # tokens don't allow.
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '*'

      - run: npm install -g $(jq -r '.packageManager' < package.json)
      - run: npm ci

      - run: npm run build
      - run: npm test

      - name: Capture new release version
        id: version
        run: |
          npx changeset version
          echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
          git restore .

      - uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          title: 'Release v${{ steps.version.outputs.version }}'
          commit: 'Release v${{ steps.version.outputs.version }}'
          version: npm run version
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
