name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    environment: npm

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          filter: blob:none

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.19.0'
          package-manager-cache: false

      - run: npm install -g "$(jq -r '.packageManager | split("+")[0]' package.json)"

      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Capture new release version
        id: version
        run: |
          npx changeset status --output "$RUNNER_TEMP/changeset-status.json"
          current_version=$(jq -r '.version' package.json)
          version=$(jq -r --arg current "$current_version" '.releases[0].newVersion // $current' "$RUNNER_TEMP/changeset-status.json")
          echo "version=$version" >> $GITHUB_OUTPUT

      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: jakebailey/hereby
          identity: release

      - uses: changesets/action@8488615a623b1b9c987934bb89eae8af6a946ac1 # v2.1.1
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          pr-title: 'Release v${{ steps.version.outputs.version }}'
          commit-message: 'Release v${{ steps.version.outputs.version }}'
          version-script: npm run version
          publish-script: npx changeset publish
