name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    environment: npm

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          filter: blob:none

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          package-manager-cache: false

      - run: npm install -g npm@latest

      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Capture new release version
        id: version
        run: |
          npx changeset version
          echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
          git restore .

      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: jakebailey/hereby
          identity: release

      - uses: changesets/action@22ccf9aa43179fe9e27dc62e575971d28cce197c # v2.0.0
        with:
          title: 'Release v${{ steps.version.outputs.version }}'
          commit: 'Release v${{ steps.version.outputs.version }}'
          version: npm run version
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
